AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'unused/**/*'

Layout/LineLength:
  IgnoredPatterns:
    - '#\s*'

Lint/DuplicateMethods:
  Enabled: false

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Metrics/BlockLength:
  IgnoredMethods:
    - tableView
    - viewDidLoad

Metrics/ClassLength:
  CountAsOne: ['array', 'hash']
  Max: 300
  Enabled: false
  
Metrics/MethodLength:
  # Enabled: false
  Max: 60
  
Metrics/AbcSize:
  Max: 40

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Alias:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/Documentation:
  Enabled: false
  
Style/OptionalBooleanParameter:
  AllowedMethods: ['initialize']

# This is because we're also using Cocoa methods
Naming/MethodName:
  # Enabled: false
  IgnoredPatterns:
    - '\Amap\s*'
    - '\A\s*tableView\s*'
    - 'tableView'
    - 'viewDidLoad'
    - 'viewWillAppear'
    - 'messageComposeViewController'
    - 'locationManager'
    - 'authUI'
    - 'textFieldShouldEndEditing'
    - 'to_CLLocationCoordinate2D'

Naming/VariableName:
  AllowedIdentifiers:
    - 'didDeselectRowAtIndexPath'
    - 'numberOfRowsInSection'
    - 'cellForRowAtIndexPath'
    - 'didFinishWithResult'
    - 'didUpdateToLocation'
    - 'fromLocation'
    - 'didFailWithError'
    - 'didSignInWithAuthDataResult'
    - 'authUI'
    - 'viewForAnnotation'
    - 'didAddAnnotationViews'
    - 'rendererForOverlay'

Naming/MethodParameterName:
  AllowedNames:
    - 'didDeselectRowAtIndexPath'
    - 'numberOfRowsInSection'
    - 'cellForRowAtIndexPath'
    - 'didFinishWithResult'
    - 'didUpdateToLocation'
    - 'fromLocation'
    - 'didFailWithError'
    - 'didSignInWithAuthDataResult'
    - 'authUI'
    - 'viewForAnnotation'
    - 'didAddAnnotationViews'
    - 'rendererForOverlay'
