AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  IgnoredMethods:
    - tableView
    - viewDidLoad

Style/FrozenStringLiteralComment:
  Enabled: false

# This is because we're also using Cocoa methods
Naming/MethodName:
  # Enabled: false
  IgnoredPatterns:
    - '\Amap\s*'

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  # Enabled: false
  Max: 40
  
Metrics/AbcSize:
  Max: 40

Style/Documentation:
  Enabled: false

Style/OptionalBooleanParameter:
  AllowedMethods: ['initialize']