// Generated by IB v1.0.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation Character
@end

@implementation CharacterController
@end

@implementation DbView
@end

@implementation DbViewController
@end

@implementation FirebaseObject
@end

@implementation Game
@end

@implementation GameController
@end

@implementation GameOld
@end

@implementation MKPolygon
@end

@implementation Pouwhenua
@end

@implementation Pylon
@end

@implementation PylonAnnotation
@end

@implementation PylonCell
@end

@implementation VoronoiMap
@end

@implementation Wakawaka
@end

@implementation JoinController
@end

@implementation Kaitarako
@end

@implementation Kapa
@end

@implementation Machine
@end

@implementation MenuController
@end

@implementation NewController
@end

@implementation Player
@end

@implementation PlayerCell
@end

@implementation BeachSection
@end

@implementation CircleEvent
@end

@implementation ClayPathMaker
@end

@implementation Edge
@end

@implementation Halfedge
@end

@implementation Scout
@end

@implementation SettingsController
@end

@implementation SplashController
@end

@implementation Takaro
@end

@implementation String
@end

@implementation Fixnum
@end

@implementation CIColor
@end

@implementation CGPoint
@end

@implementation CLLocation
@end

@implementation CLLocationCoordinate2D
@end

