// Generated by IB v1.0.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation CharacterController
@end

@implementation DbView
@end

@implementation DbViewController
@end

@implementation FirebaseObject
@end

@implementation MachineViewController
@end

@implementation GameController
@end

@implementation GameCountdownController
@end

@implementation GameOptionsController
@end

@implementation MKPolygon
@end

@implementation PouAnnotation
@end

@implementation PouSite
@end

@implementation Pouwhenua
@end

@implementation Pylon
@end

@implementation PylonAnnotation
@end

@implementation PylonCell
@end

@implementation VoronoiMap
@end

@implementation Wakawaka
@end

@implementation JoinExistingController
@end

@implementation KaitakaroFbo
@end

@implementation KapaFbo
@end

@implementation Machine
@end

@implementation MenuController
@end

@implementation NewController
@end

@implementation PlayerCell
@end

@implementation PouwhenuaFbo
@end

@implementation ClayPathMaker
@end

@implementation SelectCharacterController
@end

@implementation SettingsController
@end

@implementation SplashController
@end

@implementation TakaroFbo
@end

@implementation String
@end

@implementation Fixnum
@end

@implementation CIColor
@end

@implementation CGPoint
@end

@implementation CLLocation
@end

@implementation CLLocationCoordinate2D
@end

@implementation MKMapPoint
@end

@implementation MKMapRect
@end

@implementation Hash
@end

